spring.application.name=student-dashboard

spring.datasource.url=jdbc:postgresql://localhost:5432/student_cabinet_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

admin.secret-key=SuperSecretKey2026!@#

logging.level.com.studentdashboard=INFO
logging.file.name=logs/student-dashboard.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#отключение стандартной страницы ошибок
server.error.whitelabel.enabled=false

#выбрасывание исключения для 404
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false